project_id = "tiaxqvzthwnqgcpmttob"

[functions.send-medication-reminder]
verify_jwt = false

[functions.medication-chatbot]
verify_jwt = false

[functions.weekly-guardian-report]
verify_jwt = false

[functions.smart-reminder]
verify_jwt = false
